### ISSUE TITLE
Books Review feature

### ISSUE THREAD

**Issue by thainguyencoffee** [thainguyencoffee/bookstore-full-stack#85]
- [ ] Sách phải có thuộc tính sao ⭐ 
- [ ] Tạo và crud cho model Review (có thể đặt tên class khác hợp lý)
- [ ] Sách vừa tạo không được phép chỉ định ⭐, phải để là không có đánh giá nào, không được chỉ định là 0! phải để nó tự động đặt là không có đánh giá (có thể dùng vue để check 1 attr nào đó của json trả về dạng boolean chẳng hạn, hoặc cách khác hay hơn...)
- API Specification

| Phương thức | URL | Mô tả | Phản hồi thành công | Phải hồi thất bại |
|--------|--------|--------|--------|--------- | 
|`GET`|`/api/books/reviews`|Lấy danh sách reviews|200 OK|400 Bad Request|
|`GET`|`/api/books/{code}/reviews`|Lấy reviews theo code|200 OK|404 Not Found|
|`POST`|`/api/books/reviews`|Tạo reviews mới|201 Created|400 Bad Request|
|`PUT`|`/api/books/{code}/reviews`|Cập nhật reviews theo code|200 OK|400 Bad Request|
|`DELETE`|`/api/books/{code}/reviews`|Xóa reviews theo code|204 No Content|404 Not Found|

**Comment by hoangducduy10** [comment]
- Tôi nghĩ model Review có những thuộc tính sau: id, id_sach, user_id, rating, comment, created_at, last_modified_at
- Role được phép comment: người mua sách, quản trị viên, tác giả, người có chuyên môn

**Comment by thainguyencoffee** [comment]
> * Tôi nghĩ model Review có những thuộc tính sau: id, id_sach, user_id, rating, comment, created_at, last_modified_at
> * Role được phép comment: người mua sách, quản trị viên, tác giả, người có chuyên môn

Tôi hiểu bạn đang nói!
- Trước hết bạn cần **thêm** thuộc tính lastModifiedBy và createdBy và xóa thuộc tính user_id vì hệ thống này tích hợp với Keycloak Identify, nên server quản lý user là độc lập, không nằm trên dự án **bookstore-be**, nó sẽ nằm ở bookstore-edge. Nên nhờ Spring Data Audit module đã giúp chúng ta việc này rồi (user_id sẽ tương tự thuộc tính createdBy)

- Khi xóa thuộc tính user_id, bạn cần đảm bảo rằng có đầy đủ 4 thuộc tính data audit và annotation cho nó! nhìn code của tôi để làm theo, config sẽ tự động fill data cho 4 trường đó, bạn không cần can thiệp, 

- thứ 2. Nếu ban đầu bạn để user_id trong class đó, thì sẽ có 1 vấn đề về tính nhất quán! đó là user_id là foreign key, nó không thể null, nên không login thì không thể đánh giá được, mà như bạn có nói là cho phép người mua sách, nhưng người mua sách thì có thể là ẩn danh (chính sách hiện tại của dự án).
- Thứ 3, May mắn thay bạn xóa thuộc tính user_id và thay vào đó là 4 thuộc tính audit, nên nếu không login vẫn có thể viết review, bởi classs DataAuditConfig.java đã check . lúc này nhiệm vụ là check chỉ khi họ mua sách thì mới viết review được, không cần biết họ có login không!!! Nhưng case này phức tạp cả về UI/UX và cả BE

**Comment by thainguyencoffee** [comment]
Củng cố lại câu giải thích Xóa **user_id** là vì nó là khóa ngoại và không nên để nó vô danh
