### ISSUE TITLE
Hệ thống quản lý bình luận

### ISSUE THREAD

**Issue by nongtiensonpro** [thainguyencoffee/bookstore-full-stack#89]
1. Bộ lọc ngôn ngữ:
   - Tác giả và quản trị viên có thể tạo danh sách từ bị cấm.
   - Bộ lọc của tác giả chỉ ảnh hưởng sách của họ, quản trị viên ảnh hưởng toàn bộ hệ thống.

2. Xử lý bình luận:
   - Quản trị viên có quyền ẩn bình luận vi phạm.
   - Từ trong danh sách cấm sẽ bị chuyển thành *** khi hiển thị.
   - Bình luận chứa quá nhiều *** sẽ bị ẩn.
   - Hệ thống phản hồi nhanh cho phép người dùng chỉnh sửa bình luận trước khi bị ẩn hoàn toàn.

3. Báo cáo người dùng:
   - Người dùng có thể báo cáo bình luận vi phạm và nhận thông báo khi vấn đề được giải quyết.
   - Quản trị viên và tác giả xử lý báo cáo và thông báo kết quả qua hộp thư.
   - Hệ thống xếp hạng người dùng dựa trên lịch sử đánh giá và bình luận.

4. Công cụ phân tích và quản lý:
   - Cung cấp số liệu thống kê về bình luận và báo cáo.
   - Bảng điều khiển cho quản trị viên và tác giả để quản lý bình luận bị báo cáo.

5. Khuyến khích hành vi tích cực:
   - Tạo huy hiệu hoặc phần thưởng cho người dùng có bình luận chất lượng.

6. Quy tắc cộng đồng:
   - Công bố hướng dẫn rõ ràng về cách ứng xử và bình luận.

**Comment by thainguyencoffee** [comment]
Nên giải quyết phần này khi review thực sự push lên github, và bao gồm test
