### ISSUE TITLE
Vouchers feature

### ISSUE THREAD

**Issue by nongtiensonpro** [thainguyencoffee/bookstore-full-stack#97]
API Specification

| Phương thức | URL | Mô tả | Phản hồi thành công | Phải hồi thất bại |
|--------|--------|--------|--------|--------- | 
|`GET`|`/api/vouchers`|Lấy danh sách voucher|200 OK|400 Bad Request|
|`GET`|`/api/vouchers/{code}`|Lấy voucher theo code|200 OK|404 Not Found|
|`POST`|`/api/vouchers`|Tạo voucher mới|201 Created|400 Bad Request|
|`PUT`|`/api/vouchers/{code}`|Cập nhật voucher theo code|200 OK|400 Bad Request|
|`DELETE`|`/api/vouchers/{code}`|Xóa voucher theo code|204 No Content|404 Not Found|

Các lưu ý:

1. Validation: Kiểm tra dữ liệu đầu vào hợp lệ. Ví dụ: discount_percent phải nằm trong khoảng từ 0 đến 100, expiration_date phải là một ngày hợp lệ trong tương lai.
2. UUID: Sử dụng UUID cho khóa chính để đảm bảo tính duy nhất.
3. Concurrency Control: Sử dụng trường version để kiểm soát phiên bản và tránh xung đột dữ liệu khi cập nhật.
4. Security: Bảo mật API bằng cách sử dụng xác thực và phân quyền. Chỉ cho phép người dùng có quyền tạo, cập nhật hoặc xóa voucher.
5. Error Handling: Xử lý lỗi một cách rõ ràng và trả về mã trạng thái HTTP thích hợp kèm theo thông báo lỗi chi tiết.

CREATE TABLE vouchers
(
    id               uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    code             varchar(255) NOT NULL UNIQUE,
    discount_percent int          NOT NULL,
    expiration_date  timestamp    NOT NULL,
    created_at       timestamp    NOT NULL,
    created_by       varchar(255),
    last_modified_at timestamp    NOT NULL,
    last_modified_by varchar(255),
    version          int          NOT NULL
);

**Comment by thainguyencoffee** [comment]
@hoangducduy10  Viết spec api giống như này

**Comment by thainguyencoffee** [comment]
@nongtiensonpro Làm tới đâu rồi. Kéo nhánh main về đi 📚
